using UnityEngine;
using System;
using System.Collections;


public enum GameEventDef
{
	GAME_INIT_DONE = 0,						// 游戏初始化完毕
	VERSION_REQUEST_ING,					// 版本验证中	
	VERSION_OK,								// 版本验证成功
	VERSION_FAILED,							// 版本验证失败
	LOGIN_OK,								// 登录成功
	LOGIN_FAILED,							// 登录失败
	ROLE_GET_OK,							// 角色获取成功
	ROLE_GET_FAILED,						// 角色获取失败
	ROLE_CREATE_OK,							// 创建角色成功
	ROLE_CREATE_FAILED,						// 创建角色失败
	ENTER_GAME_OK,						    // 进游戏成功
	OPEN_PARTY,								// 打开派对
	PARTY_CREATE_OK,						// 派对创建成功
	PARTY_CREATE_FAILED,					// 派对创建失败
	PARTY_EDIT_OK,							// 派对编辑成功
	PARTY_EDIT_FAILED,						// 派对编辑失败
	MAINPLAYER_HAS_PARTY,					// 主玩家有派对
	MAINPLAYER_HASNOT_PARTY,				// 主玩家没有派对
	REQUEST_FRIEND_LIST_OK,					// 请求好友列表成功
	REQUEST_GET_FLOWER,             		// 请求获取花藤数据
	REQUEST_CREATE_FLOWER,        		// 请求创建花藤
	REQUEST_WATER,                      		// 花藤请求浇水
	REQUEST_PICK_FRUIT,               		// 请求获取花藤果实
	REQUEST_FLOWER_LOG,					// 请求获取花藤日志
	REQUEST_FLOWER_HELP,           		// 请求获取帮助
	REQUEST_FLOWER_CLOSE,				// 请求关闭瓜藤
	REQUEST_SHOW_Self_FLOWUI,         	// 显示花藤界面
	REQUEST_SHOW_Friend_FLOWUI,		// 显示花藤界面
	REQUEST_CHOICE_FLOWUI,				// 显示选择花藤界面
	REQUEST_CLEAR_STATUS,
	
	//Scene
    MSG_NOTIFY_LEAVE_SCENE,                 //离开当前场景. 这个事件取代MSG_NOTIFY_ENTER_HOUSE_SCENE.
    MSG_NOTIFY_LOVE_SCENE_LOAD_OK,          //通知love scene异步加载完成. 这是一个内部事件, 请不要使用这个事件
    MSG_NOTIFY_HOUSE_LOAD_OK,				//通知房屋模型异步加载完成, 这是一个内部事件, 请不要使用这个事件
        MSG_NOTIFY_ENTER_COMMON_SCENE,	    //通知进入公共场景
        MSG_NOTIFY_HOUSE_CREATED,			//关联MSG_NOTIFY_HOUSE_LOAD_OK之后事件, 说明房屋被创建. 建议使用这个事件. isInSelfHouse的函数可以来判定进入的房子归属. 这条消息作为进入玩家房屋的消息, 和进入公共场景区分开.
            MSG_NOTIFY_ENTER_SELF_HOUSE,	//关联MSG_NOTIFY_HOUSE_CREATED之后事件, 进入自己的房子. 建议不再使用这个事件
            MSG_NOTIFY_ENTER_FRIEND_HOUSE,	//关联MSG_NOTIFY_HOUSE_CREATED之后事件, 进入别人的房子. 建议不再使用这个事件
	
	MSG_NOTIFY_ENTER_HOUSE_SCENE,			//通知进入玩家房屋场景
	MSG_NOTIFY_ENTER_PUB_SCENE,				//通知进入酒吧场景
	//Message
	MSG_REQUEST_OPEN_MESSAGE,				//request open message main interface
	MSG_REQUEST_CLEAR_MESSAGE,				//request clear message
	MSG_REQUEST_CLEAR_NEWS,					//request clear news
//	MSG_REQUEST_SEND_MESSAGE,				//request send message
	MSG_REQUEST_DEL_MESSAGE,				//request delete message
	MSG_NOTIFY_MESSAGE_VISIT,				//request visit from message
	MSG_NOTIFY_MESSAGE_FOLLOW,				//request follow friend
	MSG_NOTIFY_MESSAGE_PERMISSION,			//request permission message
	
	MSG_NOTIFY_MESSAGE_DATA,				//notify show message data
	MSG_NOTIFY_MESSAGE_DELETE,				//notify del message
	MSG_NOTIFY_MESSAGE_ADD,					//notify add message
	
	//Friend
	MSG_REQUEST_ENTER_FRIEND_HOUSE,			//request enter friend house
	MSG_REQUEST_RETURN_HOUSE,				//request return house
	MSG_REQUEST_INVITE_FRIEND,				//request invite friend
	MSG_REQUEST_UPDATE_FRIEND_LIST_SHOW,	//request update friend list show
	MSG_REQUEST_UPDATE_FRIEND_PAGE,			//request update friend page
	MSG_REQUEST_UPDATE_OWNER_INFO,			//request update owner info
	MSG_REQUEST_UPDATE_LOVER_INFO,			//request update lover info
	MSG_REQUEST_UPDATE_FRIEND_HEADICON,		//request update friend headicon
	MSG_REQUEST_UPDATE_FRIEND_VISIT,		//request update friend visit
	MSG_REQUEST_UPDATE_FRIEND_ITEM_INFO,	//request update firend item info
	
	//Sign In
//	MSG_REQUEST_SEND_CHECKIN_CONTENT,		//request send checkin content
	MSG_REQUEST_CHECKIN_LIST,				//request checkin list
	MSG_REQUEST_CHECKIN_LAST,				//request checkin last news
	MSG_REQUEST_DEL_CHECKIN_RECORD,			//request checkin delete
	MSG_NOTIFY_CHECKIN_ADD,					//notify checkin add
	MSG_NOTIFY_CHECKIN_LAST,				//notify checkin last
	MSG_NOTIFY_CHECKIN_LIST,				//notify checkin list
	MSG_NOTIFY_CHECKIN_DEL,					//notify checkin del
	MSG_NOTIFY_CHECKIN_PERMISSION,			//notify checkin permission
	
	
	REQUEST_OPEN_UI,							// 请求打开界面
	REQUEST_CLOSE_UI,						// 请求关闭界面
	REQUEST_SHOW_FLOWER_DATA,				// 显示花藤数据
	REQUEST_PLATFORM_USER_INFO,
	NOTIFY_PLATFORM_USER_INFO,

    //Item, Pack and Currency
	ITEM_PACK_INIT,							//初始化物品包裹
	ITME_PACK_ADD_GRID,						//增加物品格(带物品)
	ITME_PACK_DEL_GRID_BEGIN,				//开始移除物品格(带物品)
	ITME_PACK_DEL_GRID_END,					//结束移除物品格(带物品)
	ITEM_PACK_UPDATE_GRID,					//更新物品格(带物品)
    LOVER_DIAMOND_CHANGE,                   //爱情水晶改变
	
	//
	MOUSE_NORMARL_STATE,					//鼠标正常状态
	MOUSE_STATE_CHANGE,						//鼠标状态改变
	PICKMGR_MOVEIN_FURNI,					//鼠标移入家具
	PICKMGR_MOVEOUT_FURNI,					//鼠标移出家具
	MOUSE_PICKED_FURNI,						//鼠标是否拾取家具
	MOUSE_USE_PROP_STATE,					//使用道具状态
	MSG_NOTIFY_FURNI_INVALID,				//update furni visible
	MSG_NOTIFY_FURNI_VALID,					//update furni visible
	
	//HOLIDAY GIFT
	MSG_NOTIFY_GIFT_ACTIVE,					//open gift interface
	MSG_NOTIFY_REQUEST_GIFT_ROLL,			//request add item
	MSG_NOTIFY_GIFT_RESULT,					//gift result
	
	//Lv Exp
	MSG_NOTIFY_LV_EXP,						//接受等级经验消息
	UPDATE_LV_EXP,							//更新等级经验
	//PhyPower
	MSG_NOTIFY_HP,							//接收体力值消息
	UPDATE_HP,								//更新体力值
	RESTORE_TIMEUP,							//体力值的倒计时到了
	PHYPOWER_TOMAX,							//体力值到达上限了
	PHYPOWER_NOTTOMAX,						//体力值没有达到上限
	//浇水泡泡定时器消息
	ENABLEWATERPP_ONTIMER,					//定时浇水泡泡显示消息
	ENABLEWATERPP_TIMECOMPLETE,				//停止浇水泡泡定时器
	DISABLEWATERPP_ONTIMER,					//
	DISABLEWATERPP_TIMECOMPLETE,			//泡泡显示的时长到消息
	
	//DRESS
	MSG_NOTIFY_INIT_DRESS_BASE_INFO,		//notify init dress info
	MSG_NOTIFY_DRESS_RESULT,				//notify dress result
	MSG_DRESS_GOLD_UPDATE,					//update dress gold show
	MSG_DRESS_RMB_UPDATE,					//update dress rmb show
	MSG_DRESS_CREDIT_UPDATE,				//update dress credit show
	MSG_DRESS_BOY_SLOT_ICON,				//boy dress slot icon
	MSG_DRESS_GIRL_SLOT_ICON,				//girl dress slot icon
	MSG_DRESS_ENABLE,						//dress ui enable
	MSG_DRESS_REFRESH_PACK_LIST,			//dress refresh pack list
	MSG_DRESS_CLEAR_BOY_SLOT_ICON,			//dress avatar slot clear
	MSG_DRESS_CLEAR_GIRL_SLOT_ICON,			//dress avatar slot clear
	
	// 走路
	MSG_STOP_WALK,							// 结束走路
	MSG_START_WALK,
	
	//FOLLOW
	MSG_NOTIFY_ADD_ATTENTION,				//notify add attention
	MSG_NOTIFY_CANCEL_ATTENTION,			//notify cancel attention
	MSG_NOTIFY_ATTENTION_LIST,				//notify attentionlist
	MSG_REFRESH_ATTENTION_INTERFACE,		//refresh attention interface
	MSG_NOTIFY_FOLLOW_ENABLE,				//enable follow UI
	
	// 公告
	MSG_SHOW_NOTICE_OVER,					// 结束显示公告
	
	// 模型相关操作事件
	MSG_MOUSE_IN_MODEL,						// 鼠标移进模型
	MSG_MOUSE_OUT_MODEL,					// 鼠标移出模型
	MSG_CLICK_PLAYER,						// 点击角色模型
	
	// 昼夜切换相关事件
	MSG_BEGIN_CHANGE_DAYNIGHT,				// 开始切换昼夜
	MSG_IN_CHANGE_DAYNIGHT,					// 正在切换昼夜
	MSG_END_CHANGE_DAYNIGHT,				// 结束切换昼夜
	
	//许愿单
	NOTIFY_WISH_ADD,
	NOTIFY_WISH_ADD_FAIL,
	NOTIFY_WISH_LIST,
	NOTIFY_CLEAR_TARGET_WISH_LIST,
	NOTIFY_TARGET_WISH_LSIT,
	NOTIFY_WISH_DEL,
	NOTIFY_SATISFY_SUCC,
	NOTIFY_SATISFY_FAIL,
	NOTIFY_WISH_RECORD,
	ADD_WISH_DATA,
	DEL_WISH_DATA,
	UPDATE_WISH_RECORD,
	TO_WISHLIST_MAX,
	
	//欢迎语
	NOTIFY_WELCOMETEXT,					//接收欢迎语
	SHOW_WELCOMETEXT,
	CLICK_OPEN_SETUPWIN,
	NOTIFY_SETWELCOME_RESULT,
	NOTIFY_SELF_WELCOMETEXT,
	
	//喇叭
	CLICK_OPENSPEAKER_BTN,
	LOAD_SPEAKERCONTENT_OK,
	SPEAKER_EDITER_UNFOCUS,
	FILL_RAND_TEXT,
	NOTIFY_SPEAKERWORD,
	ADD_SPEAKERRECORD,
	//consume
	MSG_NOTIFY_SHOW_BUY_DIALOG,			//show buy dialog
	MSG_NOTIFY_SHOW_POWER_DIALOG,		//show power dialog
	//qqhome
	MSG_NOTIFY_QQHOME_INIT,						//qqhome init
	MSG_NOTIFY_QQHOME_GIFT_GET_RESULT,			//gift get result
	MSG_NOTIFY_QQHOME_ENTRY_STATUS,				//set entry button status
	MSG_NOTIFY_QQHOME_SET_PRIVILEGE_ITEM,		//set privilege item
	MSG_NOTIFY_QQHOME_SET_PRIVILEGE_SLOT,		//set privilege gift item
	MSG_NOTIFY_QQHOME_SET_NEWER_GIFT_SLOT,		//set newer gift slot
	MSG_NOTIFY_QQHOME_SET_DAILY_SLOT,			//set daily gift slot
	MSG_NOTIFY_QQHOME_SET_DAILY_YEAR_SLOT,		//set daily gift year slot
	MSG_NOTIFY_QQHOME_SET_DAILY_SLOT_NEXT_LEVEL,//set daily gift next level slot
	
	//--self animation
	CLICK_PLAY_SANI,
	SUBMIT_REQ_START_PLAY_SANI,
	NOTIFY_PLAY_ANIMAITON,
	LOAD_FREE_SELF_ANI_ARRAY_OK,
	SELF_ANIM_END,
	NOTIFY_END_SANI,
	START_PLAY_SELF_ANI,

    //任务
    DAIYLY_TASK_REWARD,                         //日常任务的奖励变化. 参数true为已经领取所有奖励, false为还有奖励未领取
	DAIYLY_TASK_COMPLETE,
	NOTIFY_ADD_TASK,							//增加任务. 参数为任务uid
	NOTIFY_CHAIN_TASK_COMPLETE,					//链式任务完成. 参数为任务uid
	NOTIFY_CHAIN_TASK_REWARD,					//链式任务领取奖励. 参数为任务uid
	
	//friend invite
	MSG_NOTIFY_INVITE_LIST,						//friend invite list
	MSG_NOTIFY_GET_INVITE_GIFT_RESULT,			//friend invite get gift result
	MSG_NOTIFY_REFRESH_INVITE_FRIEND_LIST,		//refresh invite friend list
	MSG_NOTIFY_REFRESH_INVITE_GIFT_LIST,		//refresh invite gift list
	MSG_NOTIFY_REFRESH_INVITE_GIFT_RESULT,		//refresh invite gift list
	
	//logon award
	MSG_NOTIFY_LOGON_LIST,						//logon list
	MSG_NOTIFY_GET_LOGON_AWARD_RESULT,			//logon award result
	MSG_NOTIFY_LOGON_AWARD_ENABLE,				//logon award enable
	MSG_NOTIFY_LOGON_AWARD_ENTRANCE,			//logon entrance enable
	MSG_NOTIFY_REFRESH_AWARD_GIFT_LIST,			//logon award gift list
	MSG_NOTIFY_REFRESH_AWARD_LAST_DAY,			//logon award gift day mark
	POST_lOGONAWARDUI_CLOSE,
	
	//house update
	LOAD_HOUSERIGHTDATA_OK,
	
	//player transform
	MSG_NOTIFY_TRANSFORM_INIT,					//init transform logic
	MSG_NOTIFY_TRANSFORM_CANCEL,				//notify transform cancel
	MSG_NOTIFY_TRANSFORM_REFRESH_REMAIN_TIME,	//notify refresh remain time
	MSG_NOTIFY_USE_ITEM_WITH_PRO,				//use person pro item
	MSG_NOTIFY_ENABLE_CANCEL_USE_PROP,			//use prop start
	MSG_NOTIFY_USE_PROP_INIT_UI,				//use prop init ui
	MSG_NOTIFY_USE_PROP_END,					//use prop use end
	
	NOTIFY_HOUSE_RIGHT_GRADE,
	UPDATE_HOUSE_RIGHT_GRADE,
	MOVE_HOUSE_SUCCESS,
	HOUSELIST_PAGE_CHANGE,
	HOUSERIGHT_PAGE_CHANGE,
	NOTIFY_SPECIAL_HOUSE_LIST,
	UPDATE_SPECIAL_HOUSE_LIST,
	NOTIFY_MY_SPECIAL_HOUSE_LIST,
	UPDATE_MY_SPECIAL_HOUSE_LIST,
	MYSPECIALHOUSE_PAGE_CHANGE,
	MYPLANTUNLOCKLIST_PAGE_CHANGE,
	SPECIALHOUSE_PAGE_CHANGE,
	MSG_NOTIFY_UNLOCK_SPECIAL_HOUSE,
	MSG_NOTIFY_UNLOCK_SPECIAL_HOUSE_INFO,
	MSG_NOTIFY_GET_FREE_COUNT_FOR_MOVING_SPECIAL_HOUSE,
	
	//system board
	MSG_NOTIFY_SYSBOARD_UPDATE_CONTENT,			//update system borad content
	MSG_NOTIFY_SYSBOARD_STOP,					//stop system board
	MSG_NOTIFY_SYSBOARD_UPDATE,					//update system board content
	MSG_NOTIFY_SYSBOARD_SHOW_NOTICE,			//show system board notice ui
	
	//items make system
	MSG_NOTIFY_ITEMSMAKE_RESULT,				//notify make result
	MSG_NOTIFY_ITEMSMAKE_REFRESH_INTERFACE,		//notify refresh interface
	MSG_NOTIFY_ITEMSMAKE_ENABLE,				//notify enable ui
	
	//--
	SELECT_FRIEND_PAGE_CHANGE,
	NOTIFY_SEARCHING_ITEMS,
	UPDATE_SEARCHING_ITEMS,
	NOTIFY_COLLECT_RESULT,
	UPDATE_COLLECT_RESULT,
	NOTIFY_OPEN_START_SEARCH_UI,
	//--
	NOTIFY_SELF_MSGS,
	UPDATE_SELF_MSGS,
	
	MSG_NOTIFY_PLAYR_BUFF,
	//plant system
	MSG_NOTIFY_PLANT_LIST,						//notify plant list
	MSG_NOTIFY_PLANT_REFRESH,					//notify plant refresh(single)
	MSG_NOTIFY_PLANT_DELETE,					//notify plant delete
	MSG_NOTIFY_PLANT_PICK_FRUIT_RESULT,			//notify plant pick fruit result
	MSG_NOTIFY_PLANT_REFRESH_REMAIN_TIME,		//notify plant remain timer
	MSG_NOTIFY_PLANT_SPEED_INIT_UI,				//use prop init ui
	MSG_NOTIFY_PLANT_SPEED_END,					//use prop use end
	MSG_NOTIFY_PLANT_SPEED_REMAIN_TIME,			//speed remain time
	MSG_NOTIFY_PLANT_LIMIT_COUNT,				//notify limit count
	MSG_NOTIFY_PLANT_MAIN_UI,					//enable plant main ui
	MSG_NOTIFY_PLANT_MAIN_REFRESH_LIST_UI,		//refresh list content
	MSG_NOTIFY_PLANT_LOCK_UI,					//enable plant lock ui
	MSG_NOTIFY_PLANT_LOCK_REFRESH_UI,			//refresh lock content
	
	// 界面模态事件
	MSG_UI_MODAL_STATE,
	// 创建其他玩家
	MSG_CREATE_OTHER_PLAYER,
	// 房屋部件加载结束
	MSG_HOUSE_COMP_LOAD_FINISHED,
	// 家具交互功能按钮显示事件
	MSG_FURNI_INTERACT_FUNC_BTN_SHOW,
	//
	NOTIFY_CHAT_AROUND,
	//holiday system
	MSG_NOTIFY_HOLIDAY_LOTTERY_ACTIVE,					//notify holiday lottery active
	MSG_NOTIFY_HOLIDAY_LOTTERY_INIT,					//notify holiday lottery init
	MSG_NOTIFY_HOLIDAY_LOTTERY_RESULT,					//notify holiday lottery result
	MSG_NOTIFY_HOLIDAY_LOTTERY_REFRESH,					//notify holiday lottery refresh
	MSG_NOTIFY_HOLIDAY_LOTTERY_BOARD,					//notify holiday lottery refresh board
	
	MSG_NOTIFY_HOLIDAY_LOTTERY_ENABLE,					//notify enable ui
	MSG_NOTIFY_HOLIDAY_LOTTERY_AWARD_REFRESH,			//notify refresh award
	MSG_NOTIFY_HOLIDAY_LOTTERY_BOARD_REFRESH,			//notify refresh board
	MSG_NOTIFY_HOLIDAY_LOTTERY_RESULT_UI,				//notify lottery result
	//
	START_NEWHAND_TASK,
	COMPLETE_NEWHAND_TASK,
	CLOSE_NEWHANDTASK_UI,
	START_NEWHANDTASK_GUIDE,
	CLOSE_NEWHANDTASKGUIDEROOT,
	START_REQ_ROTATE_CAMERA,
	CLICK_CLOSE_PHOTOFRIENDUI,
	REACH_ROTATE_LEN,
	EXTENAL_CLOSE_NEWGUIDEWIN,
	OPEN_STEP_LEAD_UI,
	CLOSE_STEP_LEAD_UI,
	CLICK_TASK_BTN,
	START_MOVE_PLAYER,
	PLAYER_REACH_TARGET,
	CLICK_FITMENT_BTN,
	ENTER_FITMENT_UI,
	SELECT_FURNI_TYPE,
	SELECT_FURNI,
	SELECT_PACK_FURNI,
	UNSELECT_PACK_FURNI,
	CLICK_SAVE_FITMENT,
	PutdownStart,
	PUTDOWNEND,
	CLICK_MALL_SLOT,
	CLICK_SAVE_DRESS,
	CLICK_DALIYTASKBTN,
	HIDE_FUNC_BTNS,
	COMPLETE_NEWGUIDE_DAILYTASK,
	CLICK_GETPRIZE_BTN,
	COMPLETE_NEWGUIDE_TASKS,
	CLICK_TASK_BTN1,
	CLICK_LOVE_BTN,
	CLICK_CLOSE_CHECKIN_UI,
	LV_UPDATETO_AIM,
	CLICK_COLLECT_BTN,
	CLICK_CUT_COLLECT_TIME_BTN,
	CLICK_IMMEDIATE_DONE_BTN,
	CLICK_HOUSE_BTN,
	CONFIRM_QUIT_DRESS,
	EXIT_EDIT_HOUSE,
	RETURN_TO_TYPE_LIST,
	CLICK_SHOP_MALL_BTN,
	CLICK_SHOP_PACK_BTN,
	ADD_CHECKIN_ITEM,
	LEAVE_MAINUI,
	CLOSE_HOUSERIGHTLISTUI,
	CLICK_RIGHT_LOCK,
	BUY_HOUSE_RIGHT,
	BUY_HOUSE_RIGHT_LV_LIMITED,
	BUY_HOUSE_RIGHT_DIAMOND_LIMITED,
	CLICK_CLOSE_CONFIRMWIN,
	CLICK_MOVEHOUSE,
	CLICK_RETURN_RIGHT,
	CLICK_CLOSE_HOUSELIST,
	CLOSE_COLLECT_UI,
	CLICK_SEND_CHECKIN,
	CLICK_RIGHT_ITM_IMG,
	CLICK_ITEMS_MAKE_BTN,
	CLICK_ACTIVE_AWARD_BTN,
	OPEN_ACTIVE_AWARD_UI,
	CLICK_DAILYTASK_BTN,
	CLICK_CLOSE_DAILY_TASKUI,
	NOTIFY_ACTIVE_ITEMS_DATA,
	NOTIFY_ACTIVE_SCORES,
	NOTIFY_HAS_REWARD_LIST,
	UPDATE_DAILY_TOTAL_POINT,
	UPDATE_HAS_REWARD_LIST,
	NOTIFY_CAN_REWARD,
	CANT_REWARD,
	//npc
	MSG_NOTIFY_NPC_ADD,
	MSG_NOTIFY_NPC_DIALOG_CLOSE,
	MSG_NOTIFY_NPC_DIALOG_OPEN,
	MSG_NOTIFY_NPC_DIALOG_UI_ENABLE,
	MSG_NOTIFY_NPC_DIALOG_UI_REFRESH,
	//
	CLICK_CHUANGGUAN_BTN,
	LOAD_Q_BANK_OK,
	EXIT_CHUANGGUAN,
	NOTIFY_START_CHUANGGUAN,
	UPDATE_QUESTION_DESC,
	INIT_REMAIN_TM,
	UPDATE_REMAIN_TM,
	ANSWER_TIME_UP,
	ANSWER_WRONG,
	ANSWER_RIGHT,
	CONTINUE_CHUANGGUAN,
	CLICK_RESULT_BTN,
	UPDATE_MIND_QUIZ_COUNT,
	TO_MAX_LEVEL,
	CLICK_CLOSE_DAILY_ACTIVE,
	CLICK_CLOSE_PERSONAL_INFO_UI,
	OPEN_PERSONALINFO_UI,
	CLICK_MODIFY_PERSONALINFO,
	MSG_NOTIFY_MAIN_PLAYER_STOP_WALK,
	
	//platform
	MSG_NOTIFY_PLATFORM_TYPE_INIT,
	POINTTO_NPC,
	CLICK_NPC_IMG,
	CLICK_START_COLLECT_BTN,
	CLICK_CLOSE_BACKPACKUI,
	CLICK_ClOSE_MAKEUI,
	CLICK_MAKE,
	CLICK_RECIPE,
	OPEN_ITEMSMAKEUI,
	TASK_TARGET1_COMPLETE,
	CLICK_FLOWERPOT,
	CLICKON_FURNITURE,
	CLICK_PLANT,
	CLICK_HARVEST,
	CLICK_WATER,
	CLICK_FERTILIZE,
	CLICK_REMOVEPLANT,
	CLICK_CANCELTOSHOP,
	CLICK_CONFIRMTO_BUYSEED,
	CLICK_SEED,
	CLICK_SurePlant,
	CLICK_CANCEL_PLANT,
	ONE_NEWHAND_TASK_COMPLETE_NOREWARD,
	SELECT_PACK_FLOWERPOT,
	CLICK_RECYCLEFURNI_BTN,
	POST_NEWFLOWERPOT,
	FURNIINTERACTUI_UNENABLED,
	ROTATE_CAMERA,
	UNDO_RECYCLE_FURNI,
	POST_DLGSHOW_EVENT,
	CLICKON_OUTSIDEHOUSE,
	// 通用背包事件
	BACKPACK_OPENDED,					// 打开背包
	BACKPACK_CLOSED,					// 关闭背包
	BACKPACK_REFRESH,					// 刷新背包
	BACKPACK_CLICKED,					// 点击背包
	// 
	NOTIFY_FIRST_PAYMENT_STATUS,
	POST_FIRSTPAYMENTSTATUS,
	FIRSTPAYMENT_STATUSRESULT,
	CLICK_FIRSTPAYMENTBTN,
	GET_FIRSTPAYMENT_REWARD,
	
	//flower
	MSG_NOTIFY_REQUEST_FLOWER_FREE_COUNT,		//request free count
	MSG_NOTIFY_REQUEST_FLOWER_ROCK,				//request rock flower
	MSG_NOTIFY_REQUEST_FLOWER_LOVE_ROCK,		//request rock love
	
	MSG_NOTIFY_ENABLE_ROCK_AWARD_UI,
	MSG_NOTIFY_REFRESH_ROCK_AWARD_UI,
	MSG_NOTIFY_FLOWER_ROCK_RESULT_UI,	//rock result ui
	MSG_NOTIFY_FLOWER_FREE_INVALID,		//rock free invalid
	MSG_NOTIFY_FLOWER_FREE_REMAIN_TIME, //rock free remain time
	POST_MULTISELECTSTATE,
	PACKITEM_SELECTSTATE_CHANGED,
	TO_RESET_MULTISELECTFRAME,
	TO_UPDATE_MULTISELECTFRAME,
	CLICK_MULTISALE_BTN,
	
	//item upgrade
	MSG_NOTIFY_ITEM_TIME_DELAY_UI,					// item timelimit delay
	MSG_NOTIFY_ITEM_UPGRADE_UI,						// item upgrade
	MSG_NOTIFY_ITEM_UPGRADE_MULTI_UI,				// item upgrade list enable
	MSG_NOTIFY_ITEM_UPGRADE_LIST_REFRESH_UI,		// item upgrade list refresh
	MSG_NOTIFY_ITEM_UPGRADE_TIMECOUNT_UI,			// item upgrade list refresh
	MSG_NOTIFY_ITEM_UPGRADE_STOP_UI,				// item upgrade list refresh
	MSG_NOTIFY_ITEM_TIME_REFRESH,					// item timelimit refresh
	MSG_NOTIFY_ITEM_UPGRADE_REFRESH,				// item timelimit refresh
	MSG_NOTIFY_ITEM_UPGRADE_SUCCESS,				// item timelimit refresh
	MSG_NOTIFY_ITEM_UPGRADE_FREE_UI,				// item timelimit btn free
	
	//DragonBoatFestival
	MSG_NOTIFY_DRAGON_NORMAL_UI,					// dragon normal ui
	MSG_NOTIFY_DRAGON_SMALL_UI,						// dragon small ui
	
	//remedy
	MSG_NOTIFY_REMEDY_BUTTON_ENABLE_UI,				//remedy button ui enable
	MSG_NOTIFY_REMEDY_ENABLE_UI,					//remedy ui enable
	MSG_NOTIFY_REMEDY_DATA,							//notify remedy data
	SENDMSGTOYYSUBCHANNEL,
	// 打开/关闭ModalRoot事件
	MSG_OPEN_MODAL_ROOT,
	MSG_CLOSE_MODAL_ROOT,
	// 
	NOTIFY_PUB_LIST,
	CLICK_CLOSE_ROOT,
	CHANNEL_LIST_PAGE_CHANGE,
	CLICK_CHANNEL_SENDBTN,
	// yy语音事件
	YY_AUDIO_CREATE_ROOM,
	YY_AUDIO_ENTER_ROOM,
	YY_AUDIO_LEAVE_ROOM,
	YY_AUDIO_START_SPEAK,
	YY_AUDIO_STOP_SPEAK,
	//
	//diamond logic
	MSG_NOTIFY_SHOW_DIAMOND_BUY_UI,				//show diamond buy ui
	MSG_NOTIFY_UPDATE_DIAMOND,					//show diamond update
	CLICK_CLOSE_VoiceChannelUI,
	CLICK_MINI_VoiceChannelUI,
	NOTIFY_PARTY_SCORE_COIN,
	MSG_NOTIFY_UPDATE_CREDIT,					//show credit_update
	// 礼盒模型加载结束
	MSG_GIFT_BOX_LOAD_FINISHED,
	// 传送点粒子加载结束
	MSG_TRANSFORM_PARTICLE_LOAD_FINIESHED,
	// 家具类型解锁列表
	MSG_FURNI_TYPE_UNLOCK_LIST,
	NOTIFY_BUY_SYS_SHOP_GOODS,
	// 改变家装类型
	MSG_CHANGE_FITMENT_TYPE,
	EXCHANGELIST_PAGE_CHANGE,
	CLOSE_EXCHANGEUI,
	NOTIFY_EXCHANGE,
	CLICK_MYPLANT_TABBTN,
	CLICK_UNLOCKFLOWERPOT_BTN,
	UNLOCKFLOWERPOT,
	CLICK_SPRITE,
	CLICK_AUTO_FITMENT_BTN,
	CLICK_CHECKBUY_CHOOSE1,
	CLICK_CHECKBUY_SUREBTN,
	CLICK_CHECKBUY_CANCELBTN,
	CLICK_UPGRADE_BTN,
	CLICK_PARTY_BTN,
	CLICK_EXCHANGE_BTN,
	CLICK_ENTER_BTN,
	CLICK_ADDPHYPOWER_BTN,
	CLICK_OPENLOVENOTE_BTN,
	CLICK_GOODS_BTN,
	CLICK_CLOSE_GOODS_BTN,
	CLICK_OPEN_STORAGE_PERSON_BTN,
	CLICK_OPEN_POTOFRIEND,
	CLICK_VISIT_PHOTOFRIEND,
	CLICK_OPEN_PAIHANGBANG,
	CLICK_RANKLIST_VISIT_BTN,
	CHECK_SEED_CROP_ID,
	CLICK_ENTERTAIN_BTN,			//招待按钮
	CLOSE_ENTERTAINUI,				//关闭选择对话框
	CLICK_WAITER_BTN,				//更换侍者按钮
	CLOSE_WAITERUI,					//关闭更换侍者界面
	CLICK_BARTENDER_BTN,
	CLOSE_BARTENDERUIROOT,
	BARTENDERUI_SHOW_PAGE_CHANGE,   // 调酒面板改变子页面
	NOTIFY_UNLOCK_FOOD_EVENT,
	REFRESH_FOOD_ALL_INFOS_SUCC,
	CLICK_WAITER_FACE,				// 点击侍者头像
	CLICK_WAITER_EMPLOY_BTN,		// 点击侍者雇佣按钮
	CLICK_WAITER_UPGRADE_BTN,		// 点击侍者升级按钮
	START_EXPAND_FOOD_STOCK,
	START_EXPAND_FOOD_STOCK_GRID,
	EXPAND_FOOD_STOCK_COMPLETE,
	COMPLETE_EXPAND_FOOD_STOCK_GRID,
	POPUP_REQ_EXPANDSTOCK_CONFIRM_UI,
	SEND_STOCK_INEXPANDING_EVENT,
	NOTIFY_PRODUCE_AREA,
	NOTIFY_EXPAND_PRODUCE_AREA,
	MAKING_PRODUCT_INFO,
	ENABLE_MAKE_PRODUCT_BTN_EVENT,
	CLICK_ADDSHAKE_BTN,
	ADD_FOODPRODUCT_TO_PREMAKE,
	COMPLETE_MAKE_PRODUCTS_LIST,
	COMPLETE_MAKE_ONE_PRODUCT,
	REMOVE_PRODUCT,
	PREMAKE_STOCK_CHANGED,
	PREMAKE_STOCK_PERGRID_VALUE_CHANGED,
	ADMAKING_PRODUCT_VALUE_CHANGED,
	ATMAKING_PRODUCT_PERGRID_VALUE_CHANGED,
	CLICK_SUPPLY_STUFF_BTN,         // 点击补充材料按钮
	CLICK_UNLOCK_BARCONTAIN_BTN,    // 点击解锁调酒格子按钮    
	CLEAR_OUTSIDE_DATAS,
	CUR_STOCK_VALUE_CHANGED,
	CUR_PERGRID_STOCK_VALUE_CHANGED,
	EXPAND_FOOD_STOCK_CANCEL,
	CANCEL_EXPAND_FOOD_STOCK_GRID,
	PREMAKE_COST_VALUE_CHANGED,
	START_MAKING_PRODUCTS,
	IMMEDIATE_COMPLETE_PRODUCTS,
	MOUSEOVER_STOCK_GRID_CALLBACK,
	All_FOODRRSERVESITEM_INIT,
	MAKING_PRODUCTS_ONTIMER,
	MAKING_PRODUCTS_TIMERCOMPLETE,
	MAKING_PRODUCTS_TIMERSTART,
	STOP_MAKING_PRODUCT_TIMER,
	SET_EXPAND_USERDATA,
	REFRESH_PRODUCT_INFO,
	CLICK_FOOD_UPGRADE_BTN,
	FOOD_UPGRADE_SUCCESS,
	START_COMPLETEFOOD_TIP_TIMER,
	COMPLITE_MAKE_FOOD_TIP_TIMER,
	EXPAND_STOCK_ONTIMER,
	EXPAND_STOCK_TIMERCOMPLETE,
	OPEN_COMPLETE_EXPAND_TIP,
	CLOSE_COMPLETE_EXPAND_TIP,
	MSG_NOTIFY_CLOSE_NEW_HAND_TASK_REAWARD_UI,	// 关闭领取新手任务奖励界面
	MSG_NOTIFY_CLOSE_FOOD_SETTLEMENT_DIAMOND_UI,	// 关闭食物结算水晶界面
	MSG_NOTIFY_NEW_HAND_TASK,	// 通知新手任务
	CLICK_RUNSWITCH_BTN,
	REFRESH_BUFF_ICON,			// 通知主界面BUFF刷新
	PARTYPACK_CHANGE,  // 派对食物道具页面改变
	MSG_NOTIFY_USE_ITEM_BY_SCENE,	// 通知场景所有玩家使用了道具
}


